// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCovvv0WGem3WJgmk3QYmhfANvVhXkh3_M',
    appId: '1:45654400681:web:aeb87925ea0cbfde6913b8',
    messagingSenderId: '45654400681',
    projectId: 'one-device-can-sign-in',
    authDomain: 'one-device-can-sign-in.firebaseapp.com',
    storageBucket: 'one-device-can-sign-in.appspot.com',
    measurementId: 'G-FD21QL71PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIPMNPTu2NQWSFrTidS5jM4ATSrIa50zI',
    appId: '1:45654400681:android:822fd46e2c4044a66913b8',
    messagingSenderId: '45654400681',
    projectId: 'one-device-can-sign-in',
    storageBucket: 'one-device-can-sign-in.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbwcCVSsq02XZ-9J1bJ8OaMVmGrnpAiY0',
    appId: '1:45654400681:ios:f66da32f1b9443326913b8',
    messagingSenderId: '45654400681',
    projectId: 'one-device-can-sign-in',
    storageBucket: 'one-device-can-sign-in.appspot.com',
    iosBundleId: 'com.example.onlyOneDeviceCanLoginAtATimeUsingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbwcCVSsq02XZ-9J1bJ8OaMVmGrnpAiY0',
    appId: '1:45654400681:ios:6b4fea8b319033ba6913b8',
    messagingSenderId: '45654400681',
    projectId: 'one-device-can-sign-in',
    storageBucket: 'one-device-can-sign-in.appspot.com',
    iosBundleId: 'com.example.onlyOneDeviceCanLoginAtATimeUsingFirebase.RunnerTests',
  );
}
